name: Back End Pipeline Stage

on:
    push:
        branches:
            - master

jobs:
    validateCode:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Validate Code
              run: npm run validateCode

    buildPushGcr:
        runs-on: ubuntu-latest
        needs: validateCode

        env:
            IMAGE_NAME: backend-pipeline

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Google Cloud Auth
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
                  token_format: access_token

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Docker Auth
              uses: docker/login-action@v1
              with:
                  username: oauth2accesstoken
                  password: '${{ steps.auth.outputs.access_token }}'
                  registry: europe-central2-docker.pkg.dev

            - name: Build Docker Image
              run: docker build -t backend-pipeline .

            - name: Push Docker Image to GAR
              run: |-
                  docker tag backend-pipeline europe-central2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend-pipeline/backend-pipeline:${{ github.sha }}
                  docker push europe-central2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend-pipeline/backend-pipeline:${{ github.sha }}

            - name: Deploy to Cloud Run
              run: gcloud run deploy backend-pipeline-stage --image europe-central2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend-pipeline/backend-pipeline:${{ github.sha }} --region europe-central2

            - name: Show Output
              run: echo ${{ steps.deploy.outputs.url }}
